language: generic
sudo: required
dist: trusty

env:
  - QGIS_REPO=http://qgis.org/debian-ltr
  - QGIS_REPO=http://qgis.org/debian
  - QGIS_REPO=http://qgis.org/debian-nightly

addons: 
  apt: 
    packages: 
      - python-software-properties 

-before_install:
  - sudo apt-get -qq -y update

install:
  - sudo add-apt-repository ${QGIS_REPO}
  - sudo apt-get update
  - sudo apt-get install -y --force-yes qgis python-qgis xvfb pyqt4-dev-tools
  - sudo pip install --upgrade pip
  - sudo pip install coverage
  - sudo pip install nose
  - sudo pip install --upgrade pep8
  - sudo pip install --upgrade pylint
  - sudo pip install python-coveralls

before_script:
  - echo "Build starting on " `date`
  - export QGIS_PREFIX_PATH=/usr
  - export PYTHONPATH=${QGIS_PREFIX_PATH}/share/qgis/python/:${QGIS_PREFIX_PATH}/share/qgis/python/plugins:`pwd`
  - echo "PYTHONPATH:" $PYTHONPATH
  - export LD_LIBRARY_PATH=${QGIS_PREFIX_PATH}/lib

script:
  - pep8 --exclude=test ./
  - make pylint
  - make test

after_success:
  - coveralls

notifications:
  email:
    - mario@anche.no
